# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: holiday-kub

on:
  schedule:
    - cron:  '30 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.10.0
        run_install: true
    #  for dotenv module need to be a .env
    - name: create .env
      run: |
        touch .env
        echo BOT_ID=${{ secrets.BOT_ID }} >> .env
        echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
    - run: pnpm run task
